# Site settings
title: Audio Huta | Łukasz Rudziński
description: "Sound Designer"
url:  "https://audiohuta.com/" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Łukasz Rudziński"
  email: "studio@audiohuta.com"
  url: "https://audiohuta.com"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge
  hard_wrap: true


  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never